name: Unit Tests

on: [pull_request]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Setup project
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate

      - name: Execute tests
        run: ./gradlew test